spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
#    mongodb:
#      uri: ${MONGODB_URI}

logging:
  level:
    org.springframework.messaging: debug
    org.springframework.web.socket: debug

gachtaxi:
  auth:
    kakao:
      client: ${KAKAO_CLIENT_API_KEY}
      redirect: ${KAKAO_REDIRECT_URL}
      token_uri: ${KAKAO_TOKEN_URI}
      user_profile: ${KAKAO_USER_PROFILE}
    jwt:
      key: ${JWT_SECRET_KEY}
      accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
      refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
      cookieMaxAge: ${JWT_COOKIE_MAX_AGE}
      secureOption: ${COOKIE_SECURE_OPTION}